# Generated by Django 2.2 on 2019-05-21 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courname', models.CharField(max_length=255)),
                ('courcredit', models.SmallIntegerField()),
                ('courdescription', models.TextField(blank=True, null=True)),
                ('courseprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'courses',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufname', models.CharField(max_length=255)),
                ('stulname', models.CharField(max_length=255)),
                ('studescription', models.TextField(blank=True, null=True)),
                ('studentphone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'students',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teafname', models.CharField(max_length=255)),
                ('tealname', models.CharField(max_length=255)),
                ('teadescription', models.TextField(blank=True, null=True)),
                ('teatphone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'teachers',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=1)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicapp.Course')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicapp.Student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'grades',
                'db_table': 'grade',
            },
        ),
    ]
