# Generated by Django 2.2 on 2019-05-25 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicapp', '0002_auto_20190525_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dynamicapp.Course'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dynamicapp.Student'),
        ),
    ]
